GL-11395 Change to single action to sync everything
hexagon-geo-surv/repo-sync-action pull request #13
Opened 2023-07-25 15:36 UTC by werner-kapferer-lgs

2023-07-26 12:01 UTC, stefan-hartmann-lgs requested changes
I really like it <3 I just found a few smaller things.

2023-07-26 12:01 UTC, stefan-hartmann-lgs commented on .github/workflows/configure-deploy-key.yml
> +    schedule:
The cron is going to trigger it without any blacklist set right?

This would mean it also syncs itself which will cause the sync to fail right?

Should we not simply hard-code the blacklist and not have it as a parameter/input?

2023-07-26 12:02 UTC, stefan-hartmann-lgs commented on .github/workflows/configure-deploy-key.yml
> +              if: github.event.inputs.repository != '' && github.event.inputs.ignore != ''
Then we would also have one single step "Sync"

![image](https://github.com/hexagon-geo-surv/repo-sync-action/assets/65395387/61114e94-8711-404d-a5a5-ac214ba951e8)

2023-07-26 12:04 UTC, stefan-hartmann-lgs commented
I fear if you execute the sync without blacklisting a praticular repository it will fails. As that particular repository is too big for the runners disk. Not remember which one it was but it will be obvious once it fails 😉

2023-07-26 12:05 UTC, stefan-hartmann-lgs commented
As a final action if everthing works we could get rid of the "repo-sync-workflow-*" repos (https://github.com/hexagon-geo-surv?q=repo-sync-workflow&type=all&language=&sort=)

2023-07-26 12:06 UTC, werner-kapferer-lgs commented on .github/workflows/configure-deploy-key.yml
> +name: Sync repositories
Whoops

2023-07-26 12:07 UTC, werner-kapferer-lgs commented on .github/workflows/configure-deploy-key.yml
> +              if: github.event.inputs.repository != '' && github.event.inputs.ignore != ''
I hade a workaround before but found this solution nicer.
I can write some bash code if you want me to.

2023-07-26 12:08 UTC, werner-kapferer-lgs commented on README.adoc
> +The GitHub Action uses credentials provided by the GitHub App link:https://github.com/organizations/hexagon-geo-surv/settings/apps/reposynch[RepoSynch].
No, because `RepoSync` is reserved in GitHub for a `@reposync` user - whoever this might be.

2023-07-26 12:09 UTC, werner-kapferer-lgs commented on README.adoc
> +None
I just wanted to show off here :stuck_out_tongue:

2023-07-26 12:10 UTC, werner-kapferer-lgs commented on repo-sync.py
> +                  'an upstream repo, nor a homepage set!\nSkipping.')
But in the API it's called `homepage`?!

2023-07-26 12:10 UTC, werner-kapferer-lgs commented on .github/workflows/configure-deploy-key.yml
> +    schedule:
It would not sync itself because itself doesn't have a fork or mirror homepage set :wink:.

2023-07-26 12:11 UTC, werner-kapferer-lgs commented
> As a final action if everthing works we could get rid of the "repo-sync-workflow-*" repos (https://github.com/hexagon-geo-surv?q=repo-sync-workflow&type=all&language=&sort=)

Of course, but I would rather do it *after* this merge and validation.

2023-07-26 12:41 UTC, werner-kapferer-lgs commented on repo-sync.py
> +              default='SYNC_PRIVATE_KEY',
Done.

2023-07-26 12:42 UTC, stefan-hartmann-lgs commented on repo-sync.py
> +                  'an upstream repo, nor a homepage set!\nSkipping.')
OK that is also an argument. Matter of taste - but leave it homepage then. good for me 😉

2023-07-26 12:42 UTC, stefan-hartmann-lgs commented on .github/workflows/configure-deploy-key.yml
> +    schedule:
ahaaaa thanks

2023-07-27 06:46 UTC, werner-kapferer-lgs commented
A run over all repos: https://github.com/hexagon-geo-surv/repo-sync-action-test/actions/runs/5676869435/job/15384264876

2023-07-28 06:04 UTC, stefan-hartmann-lgs approved these changes
🚀 

Before merging one last question/info: **Leica/Hexagon specific branches on those repos can not be removed by the sync**. Can you verfiy that @werner-kapferer-lgs ? (Those contain company specific patches of those forks/mirrors)

Can we further inform @mlovato-leica @patrik-lengweiler @mathias-gopp-lgs about this change as these people are also adding forks here and there?

2023-07-28 06:08 UTC, werner-kapferer-lgs commented
> Before merging one last question/info: **Leica/Hexagon specific branches on those repos can not be removed by the sync**. Can you verfiy that @werner-kapferer-lgs ? (Those contain company specific patches of those forks/mirrors)

I took the exact same git commands that were used before. Therefore it would be a surprise if they now behave different.

2023-07-28 06:22 UTC, stefan-hartmann-lgs commented
> > Before merging one last question/info: **Leica/Hexagon specific branches on those repos can not be removed by the sync**. Can you verfiy that @werner-kapferer-lgs ? (Those contain company specific patches of those forks/mirrors)
> 
> I took the exact same git commands that were used before. Therefore it would be a surprise if they now behave different. Leica branch is still here for example: https://github.com/hexagon-geo-surv/trusted-firmware-a/tree/leica/v2.9

Yes everything is correct from this PR.

One other example of a leica specific branch would be: https://github.com/hexagon-geo-surv/googletest/tree/winceport-release-1.8.0

I think those branches should have either:

- branch protection

OR/AND

- naming convention and being exluded by the sync.

This is for me a follow-up and not this PRs problem.

What do you guys think about the leica-branch proposal @werner-kapferer-lgs @patrik-lengweiler ?

2023-07-28 06:25 UTC, stefan-hartmann-lgs commented
> > > Before merging one last question/info: **Leica/Hexagon specific branches on those repos can not be removed by the sync**. Can you verfiy that @werner-kapferer-lgs ? (Those contain company specific patches of those forks/mirrors)
> > 
> > 
> > I took the exact same git commands that were used before. Therefore it would be a surprise if they now behave different. Leica branch is still here for example: https://github.com/hexagon-geo-surv/trusted-firmware-a/tree/leica/v2.9
> 
> Yes everything is correct from this PR.
> 
> One other example of a leica specific branch would be: https://github.com/hexagon-geo-surv/googletest/tree/winceport-release-1.8.0
> 
> I think those branches should have either:
> 
> * branch protection
> 
> OR/AND
> 
> * naming convention and being exluded by the sync.
> 
> This is for me a follow-up and not this PRs problem.
> 
> What do you guys think about the leica-branch proposal @werner-kapferer-lgs @patrik-lengweiler ?

2023-07-28 06:25 UTC, stefan-hartmann-lgs commented
Sry for that:

![image](https://github.com/hexagon-geo-surv/repo-sync-action/assets/65395387/ca47fc31-d88e-49ca-a63f-bf88dc162987)

=> wrong button

2023-07-28 06:29 UTC, werner-kapferer-lgs commented
> > > Before merging one last question/info: **Leica/Hexagon specific branches on those repos can not be removed by the sync**. Can you verfiy that @werner-kapferer-lgs ? (Those contain company specific patches of those forks/mirrors)
> > 
> > 
> > I took the exact same git commands that were used before. Therefore it would be a surprise if they now behave different. Leica branch is still here for example: https://github.com/hexagon-geo-surv/trusted-firmware-a/tree/leica/v2.9
> 
> Yes everything is correct from this PR.
> 
> One other example of a leica specific branch would be: https://github.com/hexagon-geo-surv/googletest/tree/winceport-release-1.8.0
> 
> I think those branches should have either:
> 
>     * branch protection
> 
> 
> OR/AND
> 
>     * naming convention and being exluded by the sync.
> 
> 
> This is for me a follow-up and not this PRs problem.
> 
> What do you guys think about the leica-branch proposal @werner-kapferer-lgs @patrik-lengweiler ?

I don't think that upstream/mirror repos will create the same branch names as we do.
But if it would be the case, we would have a problem, yes.
Minimal risk with high impact.

2023-07-28 06:29 UTC, merged

2023-07-28 09:34 UTC, patrik-lengweiler commented
> > > > Before merging one last question/info: **Leica/Hexagon specific branches on those repos can not be removed by the sync**. Can you verfiy that @werner-kapferer-lgs ? (Those contain company specific patches of those forks/mirrors)
> > > 
> > > 
> > > I took the exact same git commands that were used before. Therefore it would be a surprise if they now behave different. Leica branch is still here for example: https://github.com/hexagon-geo-surv/trusted-firmware-a/tree/leica/v2.9
> > 
> > 
> > Yes everything is correct from this PR.
> > One other example of a leica specific branch would be: https://github.com/hexagon-geo-surv/googletest/tree/winceport-release-1.8.0
> > I think those branches should have either:
> > ```
> > * branch protection
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > OR/AND
> > ```
> > * naming convention and being exluded by the sync.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This is for me a follow-up and not this PRs problem.
> > What do you guys think about the leica-branch proposal @werner-kapferer-lgs @patrik-lengweiler ?
> 
> I don't think that upstream/mirror repos will create the same branch names as we do. But if it would be the case, we would have a problem, yes. Minimal risk with high impact.

I would propose to go for branch protection.